---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/games":
    post:
      summary: create game
      responses:
        '200':
          description: successful
  "/api/v1/games/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show game
      responses:
        '200':
          description: successful
  "/api/v1/users/show_api_key":
    post:
      summary: show_api_key user
      responses:
        '200':
          description: successful
  "/api/v1/users/regenerate_api_key":
    post:
      summary: regenerate_api_key user
      responses:
        '200':
          description: successful
  "/api/v1/users":
    post:
      summary: create user
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    Bearer:
      description: API key necessary to use API calls
      type: apiKey
      name: Authorization
      in: header
